import numpy as np
import xarray as xr
import scipy.stats as st

"""
This analysis was repeated for the ws=50 and ws=70 results, but the code is not included here since it is identical to the ws=60 code. The only difference is that the file paths have "w50" instead of "w60" in them, and that the surrogate number is lower for computational efficiency.

DATA PATHS
----------
EWS_DIR  : directory containing the computed EWS arrays (lambdas, AR1s, stds) for
           all CMIP6 models. These files are too large to include in the repository.
SURR_DIR : directory containing the surrogate trend files generated by the parallel
           processing scripts. Also not included in the repository.
"""

# Set these to the directories where your large data files are stored.
EWS_DIR  = '../../new_AR6'   # directory with CMIP6 EWS arrays
SURR_DIR = '/p/tmp/mayayami' # directory with surrogate trend files


# function to get the percentile of the last value in an array, ignoring nans
def f(x):
    if not np.isnan(x[-1]):
        x=x[~np.isnan(x)]
        return st.percentileofscore(x, x[-1])
    else:
        return np.nan


def get_pvs(true_trends,surr_trends,dim='surrogates'):
    d = true_trends.expand_dims(dim=dim, axis=0)
    d[dim]=[int(len(surr_trends[dim].values))]
    parr = xr.concat((surr_trends,d),dim=dim) # the last value on the row is the true trend
    ppvs = 1- np.apply_along_axis(f, 3, parr)/100
    return ppvs


# lambdas
lambdas = xr.open_dataset(f'{EWS_DIR}/CMIP6_lambdas_w60_rmean.nc').amoc
surr_trends=xr.open_dataset(f'{SURR_DIR}/CMIP6_surrogate_lambdas_w60_ndt_trends.nc').polyfit_coefficients.sel(degree=1)
amoc = xr.open_dataset('../data/CMIP6_amoc2.nc').amoc
cmip_trends = xr.open_dataset(f'{EWS_DIR}/CMIP6_lambdas_w60_rmean_trends.nc').polyfit_coefficients.sel(degree=1)
ppvs = get_pvs(cmip_trends,surr_trends)

# ar1s
ar1s = xr.open_dataset(f'{EWS_DIR}/CMIP6_ar1s_w60_rmean.nc').amoc
ar1_surr_trends=xr.open_dataset(f'{SURR_DIR}/CMIP6_surrogate_ar1s_w60_ndt_trends.nc').polyfit_coefficients.sel(degree=1)
ar1_cmip_trends = xr.open_dataset(f'{EWS_DIR}/CMIP6_ar1s_w60_rmean_trends.nc').polyfit_coefficients.sel(degree=1)

ar1_ppvs = get_pvs(ar1_cmip_trends,ar1_surr_trends)


stds = xr.open_dataset(f'{EWS_DIR}/CMIP6_stds_w60_rmean.nc').amoc
std_surr_trends=xr.open_dataset(f'{SURR_DIR}/CMIP6_surrogate_stds_w60_ndt_trends.nc').polyfit_coefficients.sel(degree=1)
std_cmip_trends = xr.open_dataset(f'{EWS_DIR}/CMIP6_stds_w60_rmean_trends.nc').polyfit_coefficients.sel(degree=1)

std_ppvs = get_pvs(std_cmip_trends,std_surr_trends)

full_ppvs = np.stack((ppvs,ar1_ppvs,std_ppvs),axis=0)

EWS_names = ['lambda','ar1','var']


all_EWS = xr.Dataset(
    data_vars = dict(ppvs=(['indicators','indices','models','ensemble_members'],full_ppvs)),
    coords = dict(
            indicators = xr.DataArray(EWS_names, dims="indicators", coords=dict(indicators=("indicators", EWS_names))),
            indices = amoc.indices,
            models      = amoc.models,
            ensemble_members = amoc.ensemble_members)
)

all_EWS.to_netcdf('../data/CMIP6_all_EWS_ppvs.nc')